server:
  port: 8080

rocketmq:
  producer:
    namesrvAddr: namesrv-service:9876
    group: TEST_TOPIC

logging:
  path: ./logs
  level:
    com:
      example:
        test: INFO

com:
  alipay:
    sofa:
      rpc:
        registry:
          address: sofa://registry-service:9603

spring:
  output:
    ansi:
      enable: ALWAYS
  application:
    name: test